# Generated by Django 5.0.2 on 2024-09-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mdltask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdltask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
