# Generated by Django 5.0.2 on 2024-09-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mdltask_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdltask',
            old_name='discription',
            new_name='description',
        ),
    ]
